// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sop_solve_schur_cpp
List sop_solve_schur_cpp(const arma::mat& XtX, const arma::mat& ZtX, const arma::mat& ZtZ, const arma::mat& ZtXtZ, const arma::vec& u, const arma::vec& G, const arma::mat& A11inv_cached);
RcppExport SEXP _clgam_sop_solve_schur_cpp(SEXP XtXSEXP, SEXP ZtXSEXP, SEXP ZtZSEXP, SEXP ZtXtZSEXP, SEXP uSEXP, SEXP GSEXP, SEXP A11inv_cachedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZtX(ZtXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZtZ(ZtZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ZtXtZ(ZtXtZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A11inv_cached(A11inv_cachedSEXP);
    rcpp_result_gen = Rcpp::wrap(sop_solve_schur_cpp(XtX, ZtX, ZtZ, ZtXtZ, u, G, A11inv_cached));
    return rcpp_result_gen;
END_RCPP
}
// comp_mul_groups_cpp
arma::mat comp_mul_groups_cpp(const arma::vec& gamma, const arma::mat& A, const arma::uvec& groups, const int n_coarse);
RcppExport SEXP _clgam_comp_mul_groups_cpp(SEXP gammaSEXP, SEXP ASEXP, SEXP groupsSEXP, SEXP n_coarseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_coarse(n_coarseSEXP);
    rcpp_result_gen = Rcpp::wrap(comp_mul_groups_cpp(gamma, A, groups, n_coarse));
    return rcpp_result_gen;
END_RCPP
}
// clmm_crossprod_cpp
List clmm_crossprod_cpp(const arma::mat& CGX, const arma::mat& CGZ, const arma::vec& z, const arma::vec& w);
RcppExport SEXP _clgam_clmm_crossprod_cpp(SEXP CGXSEXP, SEXP CGZSEXP, SEXP zSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type CGX(CGXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type CGZ(CGZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(clmm_crossprod_cpp(CGX, CGZ, z, w));
    return rcpp_result_gen;
END_RCPP
}
// btWb_cpp
List btWb_cpp(const arma::mat& B, const arma::vec& w, const arma::vec& z);
RcppExport SEXP _clgam_btWb_cpp(SEXP BSEXP, SEXP wSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(btWb_cpp(B, w, z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_clgam_sop_solve_schur_cpp", (DL_FUNC) &_clgam_sop_solve_schur_cpp, 7},
    {"_clgam_comp_mul_groups_cpp", (DL_FUNC) &_clgam_comp_mul_groups_cpp, 4},
    {"_clgam_clmm_crossprod_cpp", (DL_FUNC) &_clgam_clmm_crossprod_cpp, 4},
    {"_clgam_btWb_cpp", (DL_FUNC) &_clgam_btWb_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_clgam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
